name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout project
      uses: actions/checkout@v3
    - name: install composer version2
      uses: php-actions/composer@v6
      with:
        progress: yes
        version: 2
        php_version: "7.4"
    #- name: composer install missing files
    #  run: composer1 install
    - name: create directories
      run: mkdir logs
    - name: copy config
      run: cp config/_config.php config/config.php
    - name: Display PHP version
      run: php --version
    - name: run phpcs for PSR12 coding style checks
      run: php ./vendor/bin/phpcs -np --standard=PSR12 --ignore=".src/Templates" ./src
    - name: run test - php unit
      run: php ./vendor/bin/phpunit --testdox
    - name: run static code analysis - psalm
      run: php ./vendor/bin/psalm
