name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout project
      uses: actions/checkout@v1
    - name: install composer version1
      uses: php-actions/composer@v5
      with:
        progress: yes
        version: 1
        php_version: 7.2
    #- name: composer install missing files
    #  run: composer1 install
    - name: copy config
      run: cp config/_config.php config/config.php
    - name: run phpcs for PSR12 coding style checks 
      run: php7.3 ./vendor/bin/phpcs -np --standard=PSR12 --ignore=".src/Templates" ./src
    - name: run test - php unit
      run: php7.3 ./vendor/bin/phpunit --testdox
    - name: run static code analysis - psalm
      run: php7.3 ./vendor/bin/psalm
